apiVersion: v1
kind: Template
metadata:
  name: phoronix-test-client
  annotations:
    description: "Scaleable phoronix client"

objects:

- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: phoronix-test-client
  spec:
    selector:
      matchLabels:
        app: phoronix-client
    serviceName: "phoronix-client"
    replicas: ${COUNT}
    template:
      metadata:
        labels:
          app: phoronix-client
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: stress
          image: greeninja/docker-phoronix:client
          env:
            - name: PHORONIX_URL
              value: ${URL}
            - name: HTTP_PROXY
              value: ${HTTP_PROXY}
            - name: HTTPS_PROXY
              value: ${HTTP_PROXY}
            - name: http_proxy
              value: ${HTTP_PROXY}
            - name: https_proxy
              value: ${HTTP_PROXY}
          volumeMounts:
          - name: storage
            mountPath: /home/phoromatic
        runAsUser: 0
    volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
parameters:
- description: "How many pods to start in the statefulset"
  displayName: "Pod count to start"
  name: COUNT
  value: "1"
- description: "Http proxy for container to use"
  displayName: "Proxy address to add to container environment"
  name: HTTP_PROXY
  value: ""
- description: "login url"
  displayName: "Phoronix master URL (iuncluding code)"
  name: URL
  value: "http://example-phronix.com/39CZAS"
  required: true

